# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# To install:
# pre-commit install --hook-type commit-msg
#
# or, if you're not using conventional commit:
# pre-commit install

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-executables-have-shebangs
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v18.1.8
    hooks:
      - id: clang-format
        exclude: (.json)
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-lint
        exclude: (.py.cmake|Doxyfile.cmake|examples/flutter/)
      - id: cmake-format
        exclude: (.py.cmake|Doxyfile.cmake|examples/flutter/)
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [fix, feat, ci, test, chore, refactor, docs]
